name: bluematrixinteractive
favicon: null
layout_spectrum: 0.1483836779370904
typography_spectrum: 0.23442212748341262
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.6474266292061657
  lightness: 0.9598526377230883
  saturation: 0.0728863961994648
  rhythmicContrast: 0.217929222388193
purpose: []
